### ISSUE TITLE
Resize playlist/picture area

### ISSUE THREAD

**Issue by randoomdude** [rcc11/4chan-sounds-player#10]
https://user-images.githubusercontent.com/6027132/141702316-babcfb33-2951-49e4-89be-9a37b5cd8beb.mp4

Can you make it so you can control the size of the picture and playlist like the old player was able to do?

**Comment by rcc11** [comment]
@randoomdude This you? https://desuarchive.org/a/thread/226512879/#226586466
Added in [3.4.7](https://github.com/rcc11/4chan-sounds-player/releases/tag/3.4.7). Just drag the image up and down same as before.
