### ISSUE TITLE
Previous defaults to beginning of song instead of previous song

### ISSUE THREAD

**Issue by randoomdude** [rcc11/4chan-sounds-player#14]
After about 1 second hitting previous either in the player or on keybind will go back to the beggining of a song instead of the previous one making you have to double click or triple click, is there eitehr a way to turn off previous defaulting to beggining of song or make the default longer than 1 second?

**Comment by rcc11** [comment]
It's currently hard coded to 3 seconds, but I'll make it configurable and disable-able.

**Comment by rcc11** [comment]
bed1d9f9b21952ab35554088a836e3ba18dee583 Added in 3.5.0. Check the playback settings.
