### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by Jorge9811** [rcc11/4chan-sounds-player#15]
![firefox_20220821_133837085](https://user-images.githubusercontent.com/54429803/185801647-545dbaa7-a6c6-47f3-990a-2821c60f74c2.png)

**Comment by rcc11** [comment]
I can't help you with that one. The file's not available from pomf.
I think pomf filenames are 6 characters all lower case though, so it doesn't seem like a valid link. How did you make the sound image?

**Comment by rcc11** [comment]
Putting this down to a bad link.
