### ISSUE TITLE
Player doesn't work in warosu.org

### ISSUE THREAD

**Issue by FledaJohansson** [rcc11/4chan-sounds-player#27]
It behaves as if there are no soundposts in the thread
![image](https://github.com/rcc11/4chan-sounds-player/assets/98169776/602601c9-e044-4aad-8a09-84f22e3a6bb4)

**Comment by vampiricwulf** [comment]
The creator has been MIA for years now. I corrected this on my fork if you'd like to test it.
https://github.com/vampiricwulf/4chan-sounds-player

**Comment by FledaJohansson** [comment]
Works like a charm. Thank you so much, I spend 18hrs a day on /vt/ so this means a lot to me
