### ISSUE TITLE
Media controls cut off

### ISSUE THREAD

**Issue by randoomdude** [rcc11/4chan-sounds-player#4]
Usually run player on a 4:3 monitor with limited space and notice the media controls cut have when you try to run it as a taller rectangle shape, and seeking bar get's priority over volume bar can you make i so sound is always toggable by default?
![image](https://user-images.githubusercontent.com/6027132/117557217-8cf3d280-b025-11eb-84f9-2b263a8033c7.png)

**Comment by rcc11** [comment]
Sounds like what you're looking for are the control options in the display settings. You can change the priority for hiding, or prevent a control from being hidden by not including it in the list. To hide the mute button add `volume-button` wherever you want in the list. (In case you noticed the tooltip for Hide Order currently says mute, volume, and volume-bar which is incorrect)

If you don't mind the controls wrapping you can just disable Prevent Wrapping all together.

<img width="459" alt="Screenshot 2021-05-10 at 10 02 54" src="https://user-images.githubusercontent.com/64926786/117634669-123acc80-b177-11eb-833d-01f4583df95d.png">

**Comment by randoomdude** [comment]
ah that's perfect I didn't know that's how it worked thanks
