### ISSUE TITLE
Playlist is always set to repeat

### ISSUE THREAD

**Issue by Jorge9811** [rcc11/4chan-sounds-player#7]
this doesnt work on firefox the same webm plays over and over and you have to switch to the next one manually
![firefox_1206](https://user-images.githubusercontent.com/54429803/135735396-6520105f-1b7a-4862-b90d-38eb984d4868.png)

**Comment by rcc11** [comment]
@Jorge9811 I'm not able to reproduce this. The only thing I can think to check is if you have "Autoplay Next" enabled under Settings > Playback?

**Comment by siricle** [comment]
I can replicate the same issue with webm on FF 94.0.1 with ccd0's 4chanX 1.14.21.7. Both "Autoplay Next" and Repeat all are enabled.
The issue only lies with webm video. Regular 4chan External Sounds behave as expected.

**Comment by Jorge9811** [comment]
> @Jorge9811 I'm not able to reproduce this. The only thing I can think to check is if you have "Autoplay Next" enabled under Settings > Playback?

i forgot to specify but as siricle says it only happens with webm videos

it's still happening btw

also wheres this settings > playback?

i use 4chanx and oneechan and i only see their configurations

it kinda sucks because i want to listen to some webm threads and i dont want to have to manually change the webm every time one is done playing so it would be nice if it could be corrected
