### ISSUE TITLE
z.zz.fo sound posts aren't recognised

### ISSUE THREAD

**Issue by Carravan** [rcc11/4chan-sounds-player#8]
I tried with a full encoded URL, which didn't play, then I created a soundpost for that hoster via the tool and noticed that it removed "https://". Posted again like this [sound=z.zz.fo%2Fxxxx.ogg] and still didn't parse.

**Comment by rcc11** [comment]
@Carravan It needs adding to the allowed hosts in the settings. You can do that manually, but the next release will automatically add it as well.

**Comment by rcc11** [comment]
819d59d1e74c5183e38cc4a68cc1acb08f15734f in [3.4.7](https://github.com/rcc11/4chan-sounds-player/releases/tag/3.4.7)
